networks:
  docker-networks:
    name: docker-networks
    driver: bridge

volumes:
  WordPress:
    driver: local
    driver-opts:
      type : none
      o : bind
      device: /home/hdazia/data/wordpress
  MariaDB:
    driver: local
    driver-opt:
      type : none
      o : bind
      device: /home/hdazia/data/mariadb