services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    networks:
      - docker-networks
    volumes:
      - MariaDB:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - docker-networks
    volumes:
      - WordPress:/var/www/html
    env_file: .env
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: on-failure
    env_file: .env
    networks:
      - docker-networks
    volumes:
      - WordPress:/var/www/html
    secrets:
      - db_password
      - db_root_password
      - wordpress_admin_password
      - wordpress_password
    depends_on:
      - mariadb

networks:
  docker-networks:
    name: docker-networks
    driver: bridge

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hdazia/data/wordpress
  MariaDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hdazia/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  wordpress_password:
    file: ../secrets/wordpress_password.txt