services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    networks:
      - docker-networks
    volumes:
      - MariaDB:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - docker-networks
    volumes:
      - WordPress:/var/www/html
    env_file: .env
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: on-failure
    env_file: .env
    networks:
      - docker-networks
    volumes:
      - WordPress:/var/www/html
    secrets:
      - db_password
      - db_root_password
      - wordpress_admin_password
      - wordpress_password
    depends_on:
      - mariadb
  redis:
    container_name: redis
    build: requirements/bonus/redis
    restart: on-failure
    networks:
      - docker-networks
    depends_on:
      - wordpress
  adminer:
    container_name: adminer
    build: requirements/bonus/Adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - docker-networks
    depends_on:
      - mariadb
  static_site:
    container_name: static_site
    build: requirements/bonus/static_site
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - docker-networks
  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    restart: on-failure
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - WordPress:/var/www/html
    networks:
      - docker-networks
    env_file: .env
    secrets:
      - ftp_password
    depends_on:
      - wordpress
  cadvisor:
    container_name: cadvisor
    build: requirements/bonus/cadivsor
    restart: on-failure
    ports:
      - "9080:9080"
    networks:
      - docker-networks
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
networks:
  docker-networks:
    name: docker-networks
    driver: bridge

volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hdazia/data/wordpress
  MariaDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hdazia/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  wordpress_password:
    file: ../secrets/wordpress_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt