FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    vsftpd \
    && rm -rf /var/lib/apt/lists/*

COPY conf/vsftpd.conf /etc/vsftpd.conf

COPY tools/ftp.sh usr/bin
RUN chmod +x /usr/bin/ftp.sh

EXPOSE 21  50000 50009

CMD ["/usr/bin/ftp.sh"]
