FROM debian:bookworm

RUN apt-get update -y && apt-get upgrade -y \
    && apt-get -y install lighttpd \
    && rm -rf /var/lib/apt/lists/* 

COPY conf/conf /etc/lighttpd/

COPY tools/index.html /var/www/html/

EXPOSE 9090

CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]