listen=YES
listen_ipv6=NO
background=NO

#rules dyal connection
anonmous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022 # permissions dyal les fichiers li kaydirhom 

chroot_local_user=YES # kaydir chroot l users local
allow_writeable_chroot=YES 
pasv_enable=YES
pasv_min_port=50000
pasv_max_port=50009